version: "3.8"

services:
  app:
    build:
      context: .
    container_name: backendesocialnet
    command: npm start
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mongo:4.4
    container_name: dbsocialnet
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
