version: "3.8"

services:
  app:
    build:
      context: .
    container_name: appudemy
    command: npm start
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mongo:4.4
    container_name: mongodbudemy
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
